name: adler32
version: 2.0.0
author: Volk <templar.volk@yandex.com>
description: Signed ADLER-32 algorithm implementation in Dart. Works in browser, VM and flutter.
homepage: https://github.com/TemplarVolk/ADLER32
environment:
  sdk: '>=2.13.4 <3.0.0'
dev_dependencies:
  test: ^1.5.1
